-- 在 Supabase SQL Editor 中执行一次：创建访问与工具使用统计
create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  event_type text not null check (event_type in ('page_view','tool_use')),
  tool_slug text,
  path text
);

create index if not exists analytics_events_created_at_idx on public.analytics_events(created_at desc);
create index if not exists analytics_events_tool_idx on public.analytics_events(event_type,tool_slug);
alter table public.analytics_events enable row level security;
revoke all on public.analytics_events from anon, authenticated;

create or replace function public.track_analytics_event(p_event_type text,p_tool_slug text default null,p_path text default null)
returns void language plpgsql security definer set search_path=''
as $$
begin
  if p_event_type not in ('page_view','tool_use') then raise exception 'invalid event type'; end if;
  if length(coalesce(p_tool_slug,''))>80 or length(coalesce(p_path,''))>200 then raise exception 'invalid analytics payload'; end if;
  insert into public.analytics_events(event_type,tool_slug,path)
  values(p_event_type,nullif(p_tool_slug,''),nullif(p_path,''));
end;
$$;
revoke all on function public.track_analytics_event(text,text,text) from public;
grant execute on function public.track_analytics_event(text,text,text) to anon,authenticated;

create or replace function public.get_analytics_summary()
returns jsonb language plpgsql security definer set search_path=''
as $$
declare result jsonb;
begin
  if not public.is_admin() then raise insufficient_privilege; end if;
  select jsonb_build_object(
    'total_views',(select count(*) from public.analytics_events where event_type='page_view'),
    'total_tool_uses',(select count(*) from public.analytics_events where event_type='tool_use'),
    'today_views',(select count(*) from public.analytics_events where event_type='page_view' and created_at>=date_trunc('day',now())),
    'tools',coalesce((select jsonb_agg(jsonb_build_object('slug',tool_slug,'uses',uses) order by uses desc) from (select tool_slug,count(*) uses from public.analytics_events where event_type='tool_use' and tool_slug is not null group by tool_slug) t),'[]'::jsonb),
    'daily',coalesce((select jsonb_agg(jsonb_build_object('date',day_label,'views',view_count) order by bucket_day) from (select d.bucket_day,to_char(d.bucket_day,'YYYY-MM-DD') as day_label,count(e.id) as view_count from generate_series(current_date-29,current_date,interval '1 day') as d(bucket_day) left join public.analytics_events e on e.event_type='page_view' and e.created_at>=d.bucket_day and e.created_at<d.bucket_day+interval '1 day' group by d.bucket_day) as daily_rows),'[]'::jsonb)
  ) into result;
  return result;
end;
$$;
revoke all on function public.get_analytics_summary() from public,anon;
grant execute on function public.get_analytics_summary() to authenticated;