-- 在 Supabase SQL Editor 中整份执行；可从旧版安全升级
create table if not exists public.analytics_events(id bigint generated by default as identity primary key,created_at timestamptz not null default now(),event_type text not null check(event_type in('page_view','tool_use')),tool_slug text,path text);
alter table public.analytics_events add column if not exists session_id text;
alter table public.analytics_events add column if not exists referrer text;
alter table public.analytics_events add column if not exists device text;
alter table public.analytics_events add column if not exists browser text;
create index if not exists analytics_events_created_at_idx on public.analytics_events(created_at desc);
create index if not exists analytics_events_tool_idx on public.analytics_events(event_type,tool_slug);
create index if not exists analytics_events_session_idx on public.analytics_events(session_id);
alter table public.analytics_events enable row level security;
revoke all on public.analytics_events from anon,authenticated;

drop function if exists public.track_analytics_event(text,text,text);
create or replace function public.track_analytics_event(p_event_type text,p_tool_slug text default null,p_path text default null,p_session_id text default null,p_referrer text default null,p_device text default null,p_browser text default null)
returns void language plpgsql security definer set search_path=''
as $$ begin
 if p_event_type not in('page_view','tool_use') then raise exception 'invalid event type'; end if;
 if length(coalesce(p_tool_slug,''))>80 or length(coalesce(p_path,''))>200 or length(coalesce(p_session_id,''))>80 or length(coalesce(p_referrer,''))>160 then raise exception 'invalid analytics payload'; end if;
 insert into public.analytics_events(event_type,tool_slug,path,session_id,referrer,device,browser) values(p_event_type,nullif(p_tool_slug,''),nullif(p_path,''),nullif(p_session_id,''),nullif(p_referrer,''),nullif(p_device,''),nullif(p_browser,''));
end $$;
revoke all on function public.track_analytics_event(text,text,text,text,text,text,text) from public;
grant execute on function public.track_analytics_event(text,text,text,text,text,text,text) to anon,authenticated;

drop function if exists public.get_analytics_summary();
create or replace function public.get_analytics_summary(p_days integer default 30)
returns jsonb language plpgsql security definer set search_path=''
as $$ declare result jsonb; start_at timestamptz; begin
 if not public.is_admin() then raise insufficient_privilege; end if;
 p_days:=greatest(1,least(coalesce(p_days,30),365));start_at:=date_trunc('day',now())-(p_days-1)*interval '1 day';
 select jsonb_build_object(
  'days',p_days,
  'total_views',(select count(*) from public.analytics_events where event_type='page_view' and created_at>=start_at),
  'unique_visitors',(select count(distinct session_id) from public.analytics_events where event_type='page_view' and created_at>=start_at),
  'today_views',(select count(*) from public.analytics_events where event_type='page_view' and created_at>=date_trunc('day',now())),
  'total_tool_uses',(select count(*) from public.analytics_events where event_type='tool_use' and created_at>=start_at),
  'tools',coalesce((select jsonb_agg(jsonb_build_object('slug',tool_slug,'uses',uses) order by uses desc) from(select tool_slug,count(*) uses from public.analytics_events where event_type='tool_use' and created_at>=start_at and tool_slug is not null group by tool_slug)t),'[]'::jsonb),
  'daily',coalesce((select jsonb_agg(jsonb_build_object('date',day_label,'views',view_count,'visitors',visitor_count) order by bucket_day) from(select d.bucket_day,to_char(d.bucket_day,'YYYY-MM-DD')day_label,count(e.id)view_count,count(distinct e.session_id)visitor_count from generate_series(current_date-(p_days-1),current_date,interval '1 day')d(bucket_day) left join public.analytics_events e on e.event_type='page_view' and e.created_at>=d.bucket_day and e.created_at<d.bucket_day+interval '1 day' group by d.bucket_day)daily_rows),'[]'::jsonb),
  'devices',coalesce((select jsonb_agg(jsonb_build_object('name',name,'count',amount) order by amount desc) from(select coalesce(device,'unknown')name,count(*)amount from public.analytics_events where event_type='page_view' and created_at>=start_at group by device)x),'[]'::jsonb),
  'browsers',coalesce((select jsonb_agg(jsonb_build_object('name',name,'count',amount) order by amount desc) from(select coalesce(browser,'Other')name,count(*)amount from public.analytics_events where event_type='page_view' and created_at>=start_at group by browser)x),'[]'::jsonb),
  'referrers',coalesce((select jsonb_agg(jsonb_build_object('name',name,'count',amount) order by amount desc) from(select coalesce(referrer,'direct')name,count(*)amount from public.analytics_events where event_type='page_view' and created_at>=start_at group by referrer order by amount desc limit 10)x),'[]'::jsonb),
  'pages',coalesce((select jsonb_agg(jsonb_build_object('path',page_path,'views',amount) order by amount desc) from(select coalesce(path,'/')page_path,count(*)amount from public.analytics_events where event_type='page_view' and created_at>=start_at group by path order by amount desc limit 10)x),'[]'::jsonb)
 )into result;return result;end $$;
revoke all on function public.get_analytics_summary(integer) from public,anon;
grant execute on function public.get_analytics_summary(integer) to authenticated;