(() => {
  const output = document.getElementById("output");
  const message = document.getElementById("message");
  const boxes = [...document.querySelectorAll("#stacks input")];

  const RULES = {
    node: `# Node
node_modules/
npm-debug.log*
yarn-debug.log*
yarn-error.log*
pnpm-debug.log*
.npm
.yarn/
dist/
build/
.cache/
.next/
.nuxt/
.turbo/
coverage/
*.tsbuildinfo
`,
    python: `# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
env/
venv/
.venv/
ENV/
*.egg-info/
.eggs/
dist/
build/
.pytest_cache/
.mypy_cache/
.ruff_cache/
`,
    java: `# Java
*.class
*.jar
*.war
*.ear
target/
.gradle/
build/
out/
*.iml
`,
    go: `# Go
*.exe
*.exe~
*.dll
*.so
*.dylib
*.test
*.out
vendor/
`,
    rust: `# Rust
/target/
**/*.rs.bk
Cargo.lock
`,
    dotnet: `# .NET
bin/
obj/
*.user
*.suo
.vs/
packages/
`,
    macos: `# macOS
.DS_Store
.AppleDouble
.LSOverride
Icon
._*
.Spotlight-V100
.Trashes
`,
    windows: `# Windows
Thumbs.db
ehthumbs.db
Desktop.ini
$RECYCLE.BIN/
*.lnk
`,
    ide: `# IDE
.idea/
.vscode/
*.swp
*.swo
*~
.project
.classpath
.settings/
`,
    react: `# React / Next
.next/
out/
.vercel/
*.tsbuildinfo
next-env.d.ts
`,
    vue: `# Vue / Nuxt
.nuxt/
.output/
dist/
.vite/
`,
    env: `# Env & secrets
.env
.env.*
!.env.example
*.pem
*.key
secrets/
`,
  };

  function generate() {
    const selected = boxes.filter((b) => b.checked).map((b) => b.value);
    if (selected.length === 0) {
      output.value = "";
      message.textContent = "请至少勾选一项";
      message.className = "message error";
      return;
    }
    const parts = ["# Generated by Utilora", "# https://utilora.github.io/", ""];
    selected.forEach((key) => {
      if (RULES[key]) parts.push(RULES[key].trimEnd(), "");
    });
    output.value = parts.join("\n").trim() + "\n";
    message.textContent = "已生成 .gitignore";
    message.className = "message";
  }

  document.getElementById("gen").addEventListener("click", generate);
  document.getElementById("clear").addEventListener("click", () => {
    boxes.forEach((b) => (b.checked = false));
    output.value = "";
    message.textContent = "";
  });
  document.getElementById("copy").addEventListener("click", async () => {
    if (!output.value) return;
    try {
      await navigator.clipboard.writeText(output.value);
      message.textContent = "已复制";
      message.className = "message";
    } catch {
      message.textContent = "复制失败";
      message.className = "message error";
    }
  });
  document.getElementById("download").addEventListener("click", () => {
    if (!output.value) return;
    const blob = new Blob([output.value], { type: "text/plain" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = ".gitignore";
    a.click();
    URL.revokeObjectURL(a.href);
    message.textContent = "已开始下载";
    message.className = "message";
  });

  generate();
})();
